name: Notarize and Authenticate Docker Image BOM with CAS

on:
  workflow_dispatch:
  #push:
  #  branches: [main]
  workflow_run:
    workflows: ["Builder"]    
    types: [completed]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  notarize-docker-image-bom-amd64:    
      runs-on: ubuntu-latest
      steps:    
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Pull amd64 Docker image
        run: docker pull ghcr.io/bigthundersr/homeassistant-addons-bigthundersr-letsencrypt-amd64
        shell: bash
      
      - name: Notarize amd64 Docker Image BOM
          # --> Run the GitHub action
          # uses: codenotary/cas-notarize-docker-image-github-action@v1.0.0
        uses: codenotary/cas-notarize-docker-image-bom-github-action@main
        with:
          asset: docker://ghcr.io/bigthundersr/homeassistant-addons-bigthundersr-letsencrypt-amd64
          cas_api_key: ${{ secrets.CAS_API_KEY }}
      
      - name: Authenticate amd64 Docker Image
        uses: codenotary/cas-authenticate-docker-image-github-action@main
        with:
          asset: docker://ghcr.io/bigthundersr/homeassistant-addons-bigthundersr-letsencrypt-amd64
          signerID: QmlnVGh1bmRlclNSQG91dGxvb2suY29t
          
      - name: Authenticate amd64 Docker Image BOM
        uses: codenotary/cas-authenticate-docker-bom-github-action@main
        with:
          asset: docker://ghcr.io/bigthundersr/homeassistant-addons-bigthundersr-letsencrypt-amd64
          signerID: QmlnVGh1bmRlclNSQG91dGxvb2suY29t
  
  notarize-docker-image-bom-i386:    
      runs-on: ubuntu-latest
      steps:    
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Pull i386 Docker image
        run: docker pull ghcr.io/bigthundersr/homeassistant-addons-bigthundersr-letsencrypt-i386
        shell: bash
          
      - name: Notarize i386 Docker Image BOM
          # --> Run the GitHub action
          # uses: codenotary/cas-notarize-docker-image-github-action@v1.0.0
        uses: codenotary/cas-notarize-docker-image-bom-github-action@main
        with:
          asset: docker://ghcr.io/bigthundersr/homeassistant-addons-bigthundersr-letsencrypt-i386
          cas_api_key: ${{ secrets.CAS_API_KEY }}
          
      - name: Authenticate i386 Docker Image
        uses: codenotary/cas-authenticate-docker-image-github-action@main
        with:
          asset: docker://ghcr.io/bigthundersr/homeassistant-addons-bigthundersr-letsencrypt-i386
          signerID: QmlnVGh1bmRlclNSQG91dGxvb2suY29t
              
      - name: Authenticate i386 Docker Image BOM
        uses: codenotary/cas-authenticate-docker-bom-github-action@main
        with:
          asset: docker://ghcr.io/bigthundersr/homeassistant-addons-bigthundersr-letsencrypt-i386
          signerID: QmlnVGh1bmRlclNSQG91dGxvb2suY29t

  notarize-docker-image-bom-arm:
    runs-on: ubuntu-latest
    name: Run on ${{ matrix.distro }} ${{ matrix.arch }}
    
    # Run steps on a matrix of x arch/distro combinations
    strategy:
      matrix:
        include:     
          - arch: aarch64
            distro: ubuntu_latest            
          - arch: armv7
            distro: ubuntu_latest
          - arch: none
            distro: none
            base_image: aarch64/ubuntu_latest
    
    steps:    
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands on arm
        id: runcmdarm
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          
          ## Not required, but speeds up builds
          githubToken: ${{ github.token }}
          shell: /bin/bash
          install: |
            #apt-get update -y
            #apt-get install -y docker.io
            case "${{ matrix.distro }}" in
              ubuntu*|jessie|stretch|buster|bullseye)
                apt-get update -q -y
                apt-get install -q -y wget docker.io
                ;;
              fedora*)
                dnf -y update
                dnf -y install wget docker
                ;;
              alpine*)
                apk update
                apk add wget docker
                ;;
            esac
          run: |
            wget https://github.com/codenotary/cas/releases/download/v1.0.3/cas-v1.0.3-linux-arm64 -O "${PWD}/cas"
            chmod a+x "${PWD}/cas"
            export CAS_API_KEY=${{ secrets.CAS_API_KEY }}; "${PWD}/cas" login
            case "${{ matrix.arch }}" in
            aarch64)
                docker pull --platform linux/arm64 ghcr.io/bigthundersr/homeassistant-addons-bigthundersr-letsencrypt-aarch64
                "${PWD}/cas" notarize --bom docker://ghcr.io/bigthundersr/homeassistant-addons-bigthundersr-letsencrypt-aarch64
                "${PWD}/cas" authenticate --bom docker://ghcr.io/bigthundersr/homeassistant-addons-bigthundersr-letsencrypt-aarch64
                ;;            
            armv7)
                docker pull --platform linux/arm/v7 ghcr.io/bigthundersr/homeassistant-addons-bigthundersr-letsencrypt-armv7
                "${PWD}/cas" notarize --bom docker://ghcr.io/bigthundersr/homeassistant-addons-bigthundersr-letsencrypt-armv7
                "${PWD}/cas" authenticate --bom docker://ghcr.io/bigthundersr/homeassistant-addons-bigthundersr-letsencrypt-armv7
                ;;
            none)
                docker pull --platform linux/arm64 ghcr.io/bigthundersr/homeassistant-addons-bigthundersr-letsencrypt-armhf
                "${PWD}/cas" notarize --bom docker://ghcr.io/bigthundersr/homeassistant-addons-bigthundersr-letsencrypt-armhf
                "${PWD}/cas" authenticate --bom docker://ghcr.io/bigthundersr/homeassistant-addons-bigthundersr-letsencrypt-armhf
                ;;              
            esac
            
            
            
            
