name: Authenticate Assets with CAS

on:
  workflow_dispatch:
  #push:
  #  branches: [main]
  workflow_run:
    workflows: ["Notarize Assets with CAS"]    
    types: [completed]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  authenticate-assets-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Authenticate LICENSE
        #--> Run the GitHub action
        uses: codenotary/cas-authenticate-asset-github-action@main
        with:
          # Whatever asset is being authenticated, can be a target/ or dist/ compiled binary or any type of file
          # Your signerID is the only thing needed to authenticate assets, this can be provided in both base64 or plaintext, and will be the email address used to generate your API Key
          asset: LICENSE
          signerID: QmlnVGh1bmRlclNSQG91dGxvb2suY29t
      - name: Authenticate README.md        
        uses: codenotary/cas-authenticate-asset-github-action@main
        with:          
          asset: README.md
          signerID: QmlnVGh1bmRlclNSQG91dGxvb2suY29t
      - name: Authenticate repository.yaml        
        uses: codenotary/cas-authenticate-asset-github-action@main
        with:          
          asset: repository.yaml
          signerID: QmlnVGh1bmRlclNSQG91dGxvb2suY29t
          
      
      - name: Authenticate letsencrypt-bigthundersr/CHANGELOG.md     
        uses: codenotary/cas-authenticate-asset-github-action@main
        with:          
          asset: letsencrypt-bigthundersr/CHANGELOG.md
          signerID: QmlnVGh1bmRlclNSQG91dGxvb2suY29t

      - name: Authenticate letsencrypt-bigthundersr/DOCS.md     
        uses: codenotary/cas-authenticate-asset-github-action@main
        with:          
          asset: letsencrypt-bigthundersr/DOCS.md
          signerID: QmlnVGh1bmRlclNSQG91dGxvb2suY29t
          
      - name: Authenticate letsencrypt-bigthundersr/README.md     
        uses: codenotary/cas-authenticate-asset-github-action@main
        with:          
          asset: letsencrypt-bigthundersr/README.md
          signerID: QmlnVGh1bmRlclNSQG91dGxvb2suY29t

      - name: Authenticate letsencrypt-bigthundersr/build.yaml        
        uses: codenotary/cas-authenticate-asset-github-action@main
        with:          
          asset: letsencrypt-bigthundersr/build.yaml
          signerID: QmlnVGh1bmRlclNSQG91dGxvb2suY29t

      - name: Authenticate letsencrypt-bigthundersr/config.yaml        
        uses: codenotary/cas-authenticate-asset-github-action@main
        with:          
          asset: letsencrypt-bigthundersr/config.yaml
          signerID: QmlnVGh1bmRlclNSQG91dGxvb2suY29t

      - name: Authenticate letsencrypt-bigthundersr/Dockerfile        
        uses: codenotary/cas-authenticate-asset-github-action@main
        with:          
          asset: letsencrypt-bigthundersr/Dockerfile
          signerID: QmlnVGh1bmRlclNSQG91dGxvb2suY29t

      - name: Authenticate letsencrypt-bigthundersr/icon.png        
        uses: codenotary/cas-authenticate-asset-github-action@main
        with:          
          asset: letsencrypt-bigthundersr/icon.png
          signerID: QmlnVGh1bmRlclNSQG91dGxvb2suY29t

      - name: Authenticate letsencrypt-bigthundersr/logo.png        
        uses: codenotary/cas-authenticate-asset-github-action@main
        with:          
          asset: letsencrypt-bigthundersr/logo.png
          signerID: QmlnVGh1bmRlclNSQG91dGxvb2suY29t

      - name: Authenticate letsencrypt-bigthundersr/translations/en.yaml        
        uses: codenotary/cas-authenticate-asset-github-action@main
        with:          
          asset: letsencrypt-bigthundersr/translations/en.yaml 
          signerID: QmlnVGh1bmRlclNSQG91dGxvb2suY29t
      
      - name: Notarize letsencrypt-bigthundersr/rootfs/etc/cont-init.d/file-structure.sh       
        uses: codenotary/cas-authenticate-asset-github-action@main
        with:          
          asset: letsencrypt-bigthundersr/rootfs/etc/cont-init.d/file-structure.sh
          signerID: QmlnVGh1bmRlclNSQG91dGxvb2suY29t

      - name: Authenticate letsencrypt-bigthundersr/rootfs/etc/services.d/lets-encrypt/finish        
        uses: codenotary/cas-authenticate-asset-github-action@main
        with:          
          asset: letsencrypt-bigthundersr/rootfs/etc/services.d/lets-encrypt/finish 
          signerID: QmlnVGh1bmRlclNSQG91dGxvb2suY29t

      - name: Authenticate letsencrypt-bigthundersr/rootfs/etc/services.d/lets-encrypt/run        
        uses: codenotary/cas-authenticate-asset-github-action@main
        with:          
          asset: letsencrypt-bigthundersr/rootfs/etc/services.d/lets-encrypt/run
          signerID: QmlnVGh1bmRlclNSQG91dGxvb2suY29t

      